name: run update_cache.py

on:
  schedule:               #TIMES IN CENTRAL TIME
    - cron: '30 5 * * *'  # Runs every day at 11:30 AM
    - cron: '30 8 * * *'  # Runs every day at 2:30 PM
    - cron: '0 11 * * *'  # Runs every day at 5:00 PM
    - cron: '0 13 * * *'  # Runs every day at 7:00 PM
    - cron: '0 15 * * *'  # Runs every day at 9:00 PM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run cache updater
        run: |
          python update_cache.py

      - name: commit new cache
        run: |
          git config --local user.email "henryhuynguyen17@gmail.com"
          git config --local user.name "henrynguyen50"

          git add .
          # commit only if there are staged changes
          git diff --cached --quiet || git commit -m "Update cache"
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main